var CAR_LIST = [
    {
        id: 1,
        name: 'Swift Desire :UP36AL-6790',
        driver: 'Mohan Singh',
        country: 'India / UttarPradesh',
        image: 'images/car1.jpg',
        description: 'This is Car used for Transportation',
        lat: 28.5355,
        lng: 78.3910,
        runningKM: '256 KM',
        IdleTime: '3.5 Hours',
        runningTime: '5.5 Hours',
        averageSpeed: '67 KMPH',
        maxSpeed: '90 KMPH',
    },
    {
        id: 2,
        name: 'Wagon R :UP36AL-6791',
        driver: 'Rahul Singh',
        country: 'India/ UttarPradesh',
        image: 'images/car2.jpg',
        description: 'This is Car used for Transportation',
        lat: 27.5355,
        lng: 77.3910,
        runningKM: '356 KM',
        IdleTime: '3.5 Hours',
        runningTime: '5.5 Hours',
        averageSpeed: '67 KMPH',
        maxSpeed: '90 KMPH',
    },
    {
        id: 3,
        name: 'Innova :DL36AL-6792',
        driver: 'Ravi Verma',
        country: 'India/ Delhi',
        image: 'images/car3.jpg',
        description: 'This is Car used for Pick up and Drop',
        lat: 28.5355,
        lng: 77.6910,
        runningKM: '286 KM',
        IdleTime: '4.5 Hours',
        runningTime: '5.5 Hours',
        averageSpeed: '67 KMPH',
        maxSpeed: '90 KMPH',
},
     {
        id: 4,
        name: 'Maruti :DL36AL-6793',
        driver: 'Sumit Arora',
        country: 'India/ Ghaziaabad',
        image: 'images/car4.jpg',
        description: 'This is Car used for service',
        lat: 26.5355,
        lng: 76.3910,
        runningKM: '106 KM',
        IdleTime: '4.5 Hours',
        runningTime: '2.5 Hours',
        averageSpeed: '67 KMPH',
        maxSpeed: '90 KMPH',
    },
      {
        id: 5,
        name: 'Swift Desire :UP36AL-6794',
        driver: 'Gaurav Sharma',
        country: 'India/ Ghaziaabad',
        image: 'images/car5.jpg',
        description: 'This is Car used for Pick up and Drop',
        lat: 29.5355,
        lng: 79.3910,
        runningKM: '206 KM',
        IdleTime: '4.5 Hours',
        runningTime: '4.5 Hours',
        averageSpeed: '60 KMPH',
        maxSpeed: '90 KMPH',
    },
];